---
- name: homework installating the vsftpd package and starting the service and adding a user
  hosts: riyadh
  tasks:
   - name: installing the package
     yum: 
       name: vsftpd
       state: latest

   - name: create a webpage    
     copy:
       content: " hi this is a homework in which will install vsftpd pkg"
       dest: /var/www/html/index.html
  
   - name: start the service
     service: 
       name: vsftpd
       state: started
       enabled: true

   - name: add a user named fanny
     user:
       name: zara
       uid: 4007
       state: present
        



